version: "2"
services:
  - type: web
    name: line-bot-webhook
    runtime: python
    repo: https://github.com/aaronwu0804/line-bot.git
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120 --workers 1 --threads 2
    plan: free
    envVars:
      - key: PORT
        value: 8080
      - key: RENDER
        value: "true"
      - key: RENDER_SERVICE_URL
        sync: false  # 手動設定
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false  # 手動設定
      - key: LINE_CHANNEL_SECRET
        sync: false  # 手動設定
      - key: LINE_USER_ID
        sync: false  # 手動設定
      - key: CWB_API_KEY
        sync: false  # 手動設定
      - key: GEMINI_API_KEY
        sync: false  # 手動設定
    autoDeploy: true
    healthCheckPath: /health
